language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pahennig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pahennig/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker" #Name of app from AWS
  environment: "Docker-env"
  bucket_name: ""
  bucket_path: "docker" # same as app
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY